/**
 * Pre-built EIA profiles committed to the repo.
 *
 * Generated by `npm run build:profiles` — do not edit by hand. Static imports
 * (rather than a runtime directory read) keep this working in every Next.js
 * runtime and make the common case a zero-network, zero-filesystem lookup.
 */

import type { RegionProfile } from "../../types";

export const BUNDLED_PROFILES: Record<string, RegionProfile> = {};

export function bundledProfile(ba: string): RegionProfile | null {
  return BUNDLED_PROFILES[ba.toUpperCase()] ?? null;
}
